site_name: Marco Pulicanò - Offensive Security & Engineering Portfolio
site_author: Ing. Marco P.
site_description: Reportistica tecnica, assessment AD/Web/Network, threat modeling e remediation strategy.
site_url: https://marcop-sed.github.io/portfolio/

theme:
  name: material
  icon:
    logo: material/shield-key
  palette:
    # Light mode
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    # Dark mode (default)
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Light Mode
  
  font:
    text: Inter
    code: JetBrains Mono
  
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: [en, it]
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: it
          default: true
          name: Italiano
          
        - locale: en
          name: English
          

extra:
  alternate:
    - name: English
      link: /portfolio/en/
      lang: en
    - name: Italiano
      link: /portfolio/
      lang: it

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

nav:
  - 🏠 Home: index.md
  - 🔴 Offensive Security:
    - Web Application - Imagery: imagery.md
    - Network & Crypto - Expressway: expressway.md
    - AD Infrastructure - DarkZero: darkzero.md
    - Kerberos & SQL - Signed: signed.md
  - ⚙️ Projects:
    - LazyPwn CTF Orchestrator: lazypwn.md
    - Boot2Root Design - Anime Gallery: eth.md
